### ISSUE TITLE
Why is subscriptions missing from the index declarations?

### ISSUE THREAD

**Issue by donhmorris** [bhushankumarl/amazon-mws#84] opened 2019-04-02 20:45 UTC

**Comment by bhushankumarl** [comment] 2019-04-17 10:23
Duplicate of #79

**Closed by bhushankumarl** 2019-04-17 10:23 UTC

**Comment by bhushankumarl** [comment] 2019-04-17 11:21
@donhmorris
The new version has been released with a fixed and new feature.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.24
